### ISSUE TITLE
implement view for caption screens inc QR code

### ISSUE THREAD

**Issue by wlcx** [emfcamp/camptions#4]

**Comment by mstratford** [comment]
Is there a "state" where the QR code should be shown? I could try and add a QR code to the infobeamer schedule rotation instead? Would be a bigger screen for people at the back?

**Comment by blip2** [comment]
QR should be permanently visible on the stage screen at the bottom with a message like "scan QR code to see these captions on your personal device"
the stage view doesn't need to have the stage name and probably needs the text to be bigger - should be optimised for 1080 scaling (I think? though the screens are probably actually 4k)

**Comment by blip2** [comment]
probably can't be implemented in infobeamer

**Comment by mstratford** [comment]
![IMG_20240525_181853](https://github.com/emfcamp/camptions/assets/1026879/13e3d042-5940-462d-b859-04e23f597935)
I can do a generic "here are captions QR", like so. Maybe a bit more design could be put into it.

**Comment by blip2** [comment]
I like it but it also needs to show the captions + be a specific link to the venue feed
probably best being implemented in the portal

**Comment by mstratford** [comment]
Ah, sorry, wires crossed, I wasn't aiming to put the actual captions on the infobeamer stage screen, just the QR so that people can scan it etc from at the back if they need to :) The captions view indeed needs doing for the dedicated screen in venue :)

**Comment by blip2** [comment]
sorted in 416d970441a167ec5d4bdb3360ae239795e8f1b3
